/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const BadgeBlue: typeof import('./app/shared/badge')['BadgeBlue']
  const BadgeRed: typeof import('./app/shared/badge')['BadgeRed']
  const ClockStore: typeof import('./app/shared/utils')['ClockStore']
  const Controls: typeof import('./app/shared/controls')['Controls']
  const FileDisplay: typeof import('./app/shared/file-display')['FileDisplay']
  const For: typeof import('./app/shared/solid-helpers')['For']
  const FullScreenIcon: typeof import('./app/shared/icons')['FullScreenIcon']
  const GoBackIcon: typeof import('./app/shared/icons')['GoBackIcon']
  const KonstaApp: typeof import('./app/shared/konsta-app')['KonstaApp']
  const LeftIcon: typeof import('./app/shared/icons')['LeftIcon']
  const LoadingIcon: typeof import('./app/shared/icons')['LoadingIcon']
  const MenuIcon: typeof import('./app/shared/icons')['MenuIcon']
  const NumberInput: typeof import('./app/shared/text-input')['NumberInput']
  const PauseIcon: typeof import('./app/shared/icons')['PauseIcon']
  const PlayIcon: typeof import('./app/shared/icons')['PlayIcon']
  const RightIcon: typeof import('./app/shared/icons')['RightIcon']
  const Show: typeof import('./app/shared/solid-helpers')['Show']
  const Subtitle: typeof import('./app/shared/subtitle')['Subtitle']
  const TEXT_SIZES: typeof import('./app/shared/utils')['TEXT_SIZES']
  const TimeDisplay: typeof import('./app/shared/subtitle')['TimeDisplay']
  const TranscriptDisplay: typeof import('./app/shared/transcript-display')['TranscriptDisplay']
  const TranscriptIcon: typeof import('./app/shared/icons')['TranscriptIcon']
  const ValueWithPlaceholder: typeof import('./app/shared/text-input')['ValueWithPlaceholder']
  const addFileToDatabase: typeof import('./app/shared/utils')['addFileToDatabase']
  const clock: typeof import('./app/shared/utils')['clock']
  const cn: typeof import('./app/shared/utils')['cn']
  const controlState: typeof import('./app/shared/utils')['controlState']
  const createRef: typeof import('react')['createRef']
  const forwardRef: typeof import('react')['forwardRef']
  const getActiveNodes: typeof import('./app/shared/utils')['getActiveNodes']
  const getFile: typeof import('./app/shared/utils')['getFile']
  const getTextSize: typeof import('./app/shared/utils')['getTextSize']
  const getTimeElapsed: typeof import('./app/shared/utils')['getTimeElapsed']
  const getTimeElapsedAsDuration: typeof import('./app/shared/utils')['getTimeElapsedAsDuration']
  const initAndGetDb: typeof import('./app/shared/utils')['initAndGetDb']
  const lazy: typeof import('react')['lazy']
  const memo: typeof import('react')['memo']
  const nodeIsActive: typeof import('./app/shared/utils')['nodeIsActive']
  const setClock: typeof import('./app/shared/utils')['setClock']
  const setFile: typeof import('./app/shared/utils')['setFile']
  const setTextSize: typeof import('./app/shared/utils')['setTextSize']
  const setTimeElapsed: typeof import('./app/shared/utils')['setTimeElapsed']
  const startTransition: typeof import('react')['startTransition']
  const useCallback: typeof import('react')['useCallback']
  const useContext: typeof import('react')['useContext']
  const useDebugValue: typeof import('react')['useDebugValue']
  const useDeferredValue: typeof import('react')['useDeferredValue']
  const useEffect: typeof import('react')['useEffect']
  const useId: typeof import('react')['useId']
  const useImperativeHandle: typeof import('react')['useImperativeHandle']
  const useInsertionEffect: typeof import('react')['useInsertionEffect']
  const useLayoutEffect: typeof import('react')['useLayoutEffect']
  const useMemo: typeof import('react')['useMemo']
  const useReducer: typeof import('react')['useReducer']
  const useRef: typeof import('react')['useRef']
  const useSignal: typeof import('./app/shared/solid-helpers')['useSignal']
  const useState: typeof import('react')['useState']
  const useSyncExternalStore: typeof import('react')['useSyncExternalStore']
  const useTransition: typeof import('react')['useTransition']
}
// for type re-export
declare global {
  // @ts-ignore
  export type { ClockStore, Entry, DbLine } from './app/shared/utils'
  import('./app/shared/utils')
}
